[package]
name = "content-relay-macos-app"
version = "0.1.0"
description = "Content Relay macOS app"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.5", features = ["image-png", "tray-icon"] }
tauri-plugin-opener = "2.5.0"
